import journalPath from "../../drizzle/meta/_journal.json" with { type: "file" };
import bootstrapJournalPath from "../../drizzle/bootstrap/meta/_journal.json" with { type: "file" };
import migration0Path from "../../drizzle/0000_majestic_wildside.sql" with { type: "file" };
import migration1Path from "../../drizzle/0001_marvelous_proudstar.sql" with { type: "file" };

// Generated by scripts/generate-migration-assets.ts. Do not edit manually.
const migrationJournalPath = journalPath as unknown as string;
const bootstrapJournalAssetPath = bootstrapJournalPath as unknown as string;
export const embeddedMigrationFiles = [
  migrationJournalPath,
  bootstrapJournalAssetPath,
  migration0Path,
  migration1Path,
];

export function migrationsFolder(): string {
  // Referencing every asset keeps the generated SQL and journal in compiled CLIs.
  void embeddedMigrationFiles;
  return migrationJournalPath.slice(
    0,
    migrationJournalPath.lastIndexOf("/meta/_journal.json"),
  );
}

export function bootstrapMigrationsFolder(): string {
  return bootstrapJournalAssetPath.slice(
    0,
    bootstrapJournalAssetPath.lastIndexOf("/meta/_journal.json"),
  );
}
