import journalPath from "../../drizzle/meta/_journal.json" with { type: "file" };
import migration0Path from "../../drizzle/0000_lovely_the_spike.sql" with { type: "file" };

// Generated by scripts/generate-migration-assets.ts. Do not edit manually.
const migrationJournalPath = journalPath as unknown as string;
export const embeddedMigrationFiles = [migrationJournalPath, migration0Path];

export function migrationsFolder(): string {
  // Referencing every asset keeps the generated SQL and journal in compiled CLIs.
  void embeddedMigrationFiles;
  return migrationJournalPath.slice(
    0,
    migrationJournalPath.lastIndexOf("/meta/_journal.json"),
  );
}
