import { join } from "node:path";

export async function buildUi() {
  const result = await Bun.build({
    entrypoints: [join(import.meta.dir, "../src/ui/app.tsx")],
    target: "browser",
    minify: true,
    naming: "[name]-[hash].[ext]",
    define: { "process.env.NODE_ENV": JSON.stringify("production") },
  });
  if (!result.success) throw new Error(result.logs.join("\n"));
  const assets: Record<string, { body: string; type: string }> = {};
  let script = "";
  let style = "";
  for (const output of result.outputs) {
    const path = `/app/assets/${output.path.split("/").pop()}`;
    const css = path.endsWith(".css");
    assets[path] = {
      body: await output.text(),
      type: css ? "text/css; charset=utf-8" : "text/javascript; charset=utf-8",
    };
    if (css) style = path;
    else script = path;
  }
  if (!script || !style) throw new Error("Missing playground bundle.");
  const shell = `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f7f8f6"><title>LocalBase</title><link rel="stylesheet" href="${style}"><script type="module" src="${script}"></script></head><body><div id="root"></div></body></html>`;
  await Bun.write(
    join(import.meta.dir, "../src/ui/assets.generated.ts"),
    `// Generated by scripts/build-ui.ts.\nexport const shell = ${JSON.stringify(shell)};\nexport const assets: Record<string, {body: string; type: string}> = ${JSON.stringify(assets)};\n`,
  );
}

if (import.meta.main) await buildUi();
