import { readdirSync } from "node:fs";
import { join } from "node:path";

const migrationsDir = "drizzle";
const tags = readdirSync(migrationsDir)
  .filter((name) => /^\d+_.+\.sql$/.test(name))
  .sort()
  .map((name) => name.slice(0, -".sql".length));

const imports = [
  'import journalPath from "../../drizzle/meta/_journal.json" with { type: "file" };',
  'import bootstrapJournalPath from "../../drizzle/bootstrap/meta/_journal.json" with { type: "file" };',
  ...tags.map(
    (tag, index) =>
      `import migration${index}Path from "../../drizzle/${tag}.sql" with { type: "file" };`,
  ),
];
const paths = tags.map((_, index) => `migration${index}Path`);
const source = `${imports.join("\n")}

// Generated by scripts/generate-migration-assets.ts. Do not edit manually.
const migrationJournalPath = journalPath as unknown as string;
const bootstrapJournalAssetPath = bootstrapJournalPath as unknown as string;
export const embeddedMigrationFiles = [
  migrationJournalPath,
  bootstrapJournalAssetPath,
  ${paths.join(", ")},
];

export function migrationsFolder(): string {
  // Referencing every asset keeps the generated SQL and journal in compiled CLIs.
  void embeddedMigrationFiles;
  return migrationJournalPath.slice(
    0,
    migrationJournalPath.lastIndexOf("/meta/_journal.json"),
  );
}

export function bootstrapMigrationsFolder(): string {
  return bootstrapJournalAssetPath.slice(
    0,
    bootstrapJournalAssetPath.lastIndexOf("/meta/_journal.json"),
  );
}
`;

await Bun.write(join("src", "db", "migration-assets.ts"), source);
