export const migrationAssetsPath = "src/db/migration-assets.ts";
const migrationsDir = "drizzle";
const journalPath = `${migrationsDir}/meta/_journal.json`;
const migrationFilePattern = /^(\d+_.+)\.sql$/;
const migrationGlob = new Bun.Glob("*.sql");

type MigrationJournal = {
  entries: Array<{ idx: number; tag: string }>;
};

function migrationTags(): string[] {
  return [...migrationGlob.scanSync({ cwd: migrationsDir, onlyFiles: true })]
    .flatMap((name) => {
      const match = migrationFilePattern.exec(name);
      return match ? [match[1]] : [];
    })
    .sort();
}

async function journalTags(): Promise<string[]> {
  const journal = (await Bun.file(journalPath).json()) as MigrationJournal;
  if (!Array.isArray(journal.entries)) {
    throw new Error("Drizzle migration journal entries are invalid.");
  }
  const tags = journal.entries.map((entry, index) => {
    if (
      !entry ||
      entry.idx !== index ||
      typeof entry.tag !== "string" ||
      !migrationFilePattern.test(`${entry.tag}.sql`)
    ) {
      throw new Error(`Drizzle migration journal entry ${index} is invalid.`);
    }
    return entry.tag;
  });
  return tags;
}

export function assertMigrationAgreement(
  files: string[],
  journal: string[],
): void {
  if (new Set(journal).size !== journal.length) {
    throw new Error("Drizzle migration journal contains duplicate tags.");
  }
  if (
    files.length !== journal.length ||
    files.some((tag, index) => tag !== journal[index])
  ) {
    throw new Error(
      "Drizzle SQL files and migration journal must agree exactly in order.",
    );
  }
}

export async function migrationAssetSource(): Promise<string> {
  const files = migrationTags();
  const journal = await journalTags();
  assertMigrationAgreement(files, journal);

  const imports = [
    'import journalPath from "../../drizzle/meta/_journal.json" with { type: "file" };',
    ...journal.map(
      (tag, index) =>
        `import migration${index}Path from "../../drizzle/${tag}.sql" with { type: "file" };`,
    ),
  ];
  const paths = journal.map((_, index) => `  migration${index}Path,`);
  return `${imports.join("\n")}

// Generated by scripts/generate-migration-assets.ts. Do not edit manually.
const migrationJournalPath = journalPath as unknown as string;
// prettier-ignore
export const embeddedMigrationFiles = [
  migrationJournalPath,
${paths.join("\n")}
];

export function migrationsFolder(): string {
  // Referencing every asset keeps the generated SQL and journal in compiled CLIs.
  void embeddedMigrationFiles;
  return migrationJournalPath.slice(
    0,
    migrationJournalPath.lastIndexOf("/meta/_journal.json"),
  );
}
`;
}
